server:
  port: 8086
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: DEMO-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/demo/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**